#  Move logs and other inputs required by the second module into directories
#  appropriate for the test samples. These were generated by running the first
#  half for each set of test samples, using default settings, with the
#  exception of the use of '--trim_mode "force"' instead of the default of
#  '--trim_mode "adaptive"'.

library('here')

for (pairing in c('single', 'paired')) {
    if (pairing == 'paired') {
        bam_type = 'cfus'
        fastqc_dir_phrase = c('_1_fastqc', '_2_fastqc')
    } else {
        bam_type = 'mfus'
        fastqc_dir_phrase = '_trimmed_fastqc'
    }
    
    for (species in c('human', 'mouse')) {
        #  For each of the sets of test samples, the first module was run,
        #  creating an output folder of the form below.
        out_dir = here('test', paste('out', species, pairing, sep='_'))
        
        dest_base_dir = here('test', species, pairing)
        
        #  The script 'scripts/prepare_test_files.R' can be used to generate
        #  each of the 'samples.manifest' files, which is a prerequisite for
        #  running this script
        man = read.table(file.path(dest_base_dir, 'samples.manifest'))
        ids = man[,ncol(man)]
        
        #  The paths to the the already-generated first-module outputs, which
        #  are to be moved into a structure compatible with the pipeline
        arioc_logs = file.path(out_dir, 'Arioc', 'logs', paste0(ids, '_alignment.log'))
        trim_logs = file.path(out_dir, 'Trimming', paste0(ids, '_was_trimmed.log'))
        fastqc_dirs = file.path(out_dir, 'FastQC', 'Trimmed', as.vector(outer(ids, fastqc_dir_phrase, paste0)))
        bams = file.path(out_dir, 'FilteredAlignments', 'bams', paste0(ids, '.', bam_type, '.bam'))
        bais = file.path(out_dir, 'FilteredAlignments', 'bams', paste0(ids, '.', bam_type, '.bam.bai'))
        
        dir.create(file.path(dest_base_dir, 'logs'))
        dir.create(file.path(dest_base_dir, 'bam'))
        
        #  Copy the first-module outputs to the destination directories
        file.copy(arioc_logs, file.path(dest_base_dir, 'logs'))
        file.copy(trim_logs, file.path(dest_base_dir, 'logs'))
        file.copy(fastqc_dirs, file.path(dest_base_dir, 'logs'), recursive=TRUE)
        file.copy(bams, file.path(dest_base_dir, 'bam'))
        file.copy(bais, file.path(dest_base_dir, 'bam'))
    }
}
