name: pipeline_env
channels:
    - conda-forge
    - bioconda
dependencies:
    - r-essentials
    - r-base
    - bioconductor-biocinstaller
    - c-compiler
    - cudatoolkit-dev
    - cxx-compiler
    - bismark=0.23.0
    - fastqc=0.11.8
    - kallisto=0.46.1
    - methyldackel=0.6.0
    - samblaster=0.1.26
    - samtools=1.12
    - trim-galore=0.6.6
    