# Software {#software}

[INSERT PIPELINE NAME HERE] makes use of several external software tools. The pipeline additionally supports the use of these tools via docker containers- this section also documents the docker images used in this mode.

## Software Versions

Here is the full list of software used by this pipeline:
    
Software | Version | Command used by the pipeline |
| ----- | ---- | ------- |
|[Arioc](https://github.com/RWilton/Arioc) | 1.43 | `AriocE`, `AriocP`, `AriocU` |
|[Bismark](https://www.bioinformatics.babraham.ac.uk/projects/bismark/) | 0.23.0 | `bismark_prepare_genome`, `bismark_methylation_extractor`, `bismark2bedgraph`, `coverage2cytosine` |
|[cmake](https://cmake.org/) | latest | `cmake` |
|[fastQC](http://www.bioinformatics.babraham.ac.uk/projects/fastqc) | 0.11.8 | `fastqc` |
|[htslib](http://www.htslib.org/download/) | 1.12 | (software library) |
|[libBigWig](https://github.com/dpryan79/libBigWig) | 0.4.6 | (software library) |
|[java](http://www.oracle.com/technetwork/java/javase/downloads/index.html) | 8+ | `java` |
|[kallisto](https://pachterlab.github.io/kallisto/source) | 0.46.1 | `kallisto` |
|[MethylDackel](https://github.com/dpryan79/MethylDackel) | 0.5.2 | `MethylDackel extract` |
|[nextflow](https://www.nextflow.io/docs/latest/getstarted.html) | >=0.27.0 (tested with 20.01.0) | `nextflow` |
|[R](https://www.r-project.org/) | user-dependent | `Rscript` |
|[samblaster](https://github.com/GregoryFaust/samblaster) | v.0.1.26 | `samblaster` |
|[samtools](http://www.htslib.org/download/) | 1.10 | `samtools` |
|[Trim Galore!](https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/) | 0.6.6 | `trim_galore` |

## Docker Images {#docker-images}

The following image versions are used in this pipeline. These are automatically managed by [INSERT PIPELINE NAME HERE].

| Image | Tag | Software |
| ----- | ---- | ------- |
| libddocker/arioc | 1.43 | Arioc |
| libddocker/bioc_kallisto | 3.11 | R 4.1.0, Bioconductor 3.11, Kallisto 0.46.1 |
| libddocker/bismark | 0.23.0 | Bismark |
| libddocker/filter_alignments | 1.0 | samtools 1.10, samblaster v.0.1.26 |
| libddocker/kallisto | 0.46.1 | Kallisto |
| libddocker/methyldackel | 0.5.2 | MethylDackel, samtools 1.10 |
| libddocker/quality_and_trim | 0.6.6 | FastQC 0.11.8, Cutadapt (latest), Trim Galore 0.6.6 |
| libddocker/ubuntu16.04_base | 1_v3 | Ubuntu Base |
