# Example Analysis

This is a work in progress!

## Add Experiment Metadata to BiocMAP Outputs

```{r, eval=FALSE}
#  Load required R packages
library('bsseq')
library('HDF5Array')
library('ggplot2')

#  Later these should changed (not hardcoded!)
meta_file = '/dcl02/lieber/ajaffe/FlowRNA_RNAseq/WGBS/FlowRNA_WGBS_Sample_Information_with_Pheno_Info.csv'
out_dir = '/dcs04/lieber/lcolladotor/flowRNA_LIBD001/flowRNA_WGBS/processed-data/03_BiocMAP/BiocMAP_output'

#  Load the 'CpG'-context object
bs_cpg = loadHDF5SummarizedExperiment(
    file.path(out_dir, 'BSobjects', 'objects', 'combined'),
    prefix = 'CpG'
)

#  Load the 'CpH'-context object. Note: this requires quite a bit of memory
#  (~23GB) even though the assays are disk-backed!
bs_cph = loadHDF5SummarizedExperiment(
    file.path(out_dir, 'BSobjects', 'objects', 'combined'),
    prefix = 'CpH'
)

#  Read in experiment-specific metadata and ensure sample ID orders match
meta = read.csv(meta_file)
meta = meta[match(colnames(bs_cpg), meta$LIBD.),]

#  Add this metadata to the Bioconductor objects
colData(bs_cpg) = cbind(colData(bs_cpg), meta)
colData(bs_cph) = cbind(colData(bs_cph), meta)

#  Keep a copy of the metadata as a data frame, for easy plotting
meta_df = data.frame(colData(bs_cpg))
```

## Exploratory Plots

### Bisulfite-Conversion Efficiency by Cell Population

```{r, eval=FALSE}
ggplot(meta_df, aes(x = Cell.Population, y = lambda_bs_conv_eff)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point()
```

### Relationship between Methylation Fractions across Cytosine Context, by Cell Population

```{r, eval=FALSE}
#  Clean this up: code should be written around the idea we are plotting each
#  combination of methylation fractions (CpG, CHG, CHH), and plots should be
#  placed in a single grid

ggplot(meta_df, aes(x = perc_M_CpG, y = perc_M_CHG)) +
    geom_point(color = Cell.Population)

ggplot(meta_df, aes(x = perc_M_CpG, y = perc_M_CHH)) +
    geom_point(color = Cell.Population)

ggplot(meta_df, aes(x = perc_M_CHG, y = perc_M_CHH)) +
    geom_point(color = Cell.Population)
```

### Fraction of Covered Cytosines by Cell Population

```{r, eval=FALSE}
#  The matrices in 'assays(bs_cpg)' and 'assays(bs_cph)' are stored on disk. To
#  speed up some below computations, we raise the per-block memory size
setAutoBlockSize(1e9)

#  Get the proportion of cytosines in each object (context) that have non-zero
#  coverage in at least one sample
meta_df$frac_covered_c_cpg = DelayedArray::colMeans(assays(bs_cpg)$Cov > 0)
meta_df$frac_covered_c_cph = DelayedArray::colMeans(assays(bs_cph)$Cov > 0)

ggplot(meta_df, aes(x = Cell.Population, y = frac_covered_c_cpg)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(position = "jitter") +
    labs(title = "Fraction of covered cytosines in CpG context")

ggplot(meta_df, aes(x = Cell.Population, y = frac_covered_c_cph)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(position = "jitter") +
    labs(title = "Fraction of covered cytosines in CpH context")
```
